name: Build WotW Rando

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_branch.outputs.branch }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Branch
        id: get_branch
        run: |
          branch=$(git branch -r --contains ${{ github.ref }} | grep -oP 'origin/\K\w+' | tail -1)
          echo branch=$branch
          echo ref=${{ github.ref }}
          echo ::set-output name=branch::$branch
  build:
    runs-on: windows-2019
    needs: meta
    steps:
      - name: Meta info
        run: |
          echo branch=${{ needs.meta.outputs.branch }}
          echo ref=${{ github.ref }}
      - name: Set up directories
        run: "md -Path 'C:\\moon\\randomizer'"
      - name: Extract tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v?([^-]*)"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install MSVC developer tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0.1"
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Generate solution
        shell: cmd
        run: "gen_win64_vs2019.bat"
      - name: Compile Wotw Rando
        shell: cmd
        run: |
          msbuild -t:CMakePredefinedTargets\INSTALL_RUNTIME -p:Configuration=RelWithDebInfo -p:Platform=x64 build\win64\WotWRandomizer.sln
          IF ERRORLEVEL 1 (
            echo BUILD FAILED
            exit 1
          )
      - name: Build Seedgen
        shell: cmd
        run: |
          cd projects/SeedgenCli
          cargo build --release
          echo Copying seedgen.exe
          copy ".\target\release\seedgen.exe" "C:\moon\randomizer\seedgen.exe"
          echo Zipping headers_presets.zip
          C:\ProgramData\Chocolatey\bin\7z.exe a -tzip C:\moon\randomizer\headers_presets.zip headers presets
          echo Copying loc_data.csv
          copy ".\loc_data.csv" "C:\moon\randomizer\loc_data.csv" /Y
          echo Copying state_data.csv
          copy ".\state_data.csv" "C:\moon\randomizer\state_data.csv" /Y
          echo Copying areas.wotw
          copy ".\areas.wotw" "C:\moon\randomizer\areas.wotw" /Y
      - name: Write version file
        shell: bash
        run: |
          echo Writing version file...
          (if [[ -n "$GIT_TAG_NAME" ]]; then echo -n "$GIT_TAG_NAME"; else echo -n "develop"; fi) > VERSION
          cp -f VERSION /c/moon/randomizer/VERSION
      - name: Compiling AHK scripts
        shell: cmd
        timeout-minutes: 1
        run: |
          ".\ext\ahk\Ahk2Exe.exe" /silent /verbose /in ".\projects/AutoTracker/OriAutoTracker.ahk" /icon ".\WotwRando.ico" /out "C:\moon\ItemTracker.exe" > error.txt
          type error.txt
      - name: Archive randomizer
        uses: actions/upload-artifact@v2
        with:
          name: randomizer
          path: 'C:\moon\randomizer\*'
