name: Build WotW Rando

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_branch.outputs.branch }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Branch
        id: get_branch
        run: |
          branch=$(git branch -r --contains ${{ github.ref }} | grep -oP 'origin/\K\w+' | tail -1)
          echo branch=$branch
          echo ref=${{ github.ref }}
          echo ::set-output name=branch::$branch
  build:
    runs-on: windows-2019
    needs: meta
    steps:
      - name: Enable Git support for long file paths
        run: git config --system core.longpaths true
      - name: Meta info
        run: |
          echo branch=${{ needs.meta.outputs.branch }}
          echo ref=${{ github.ref }}
      - name: Set up directories
        run: "md -Path 'C:\\moon\\randomizer'"
      - name: Extract tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v?([^-]*)"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install MSVC developer tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          arch: x64
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Generate solution
        shell: cmd
        run: "gen_win64_vs2019.bat"
      - name: Compile Wotw Rando
        shell: cmd
        run: |
          msbuild -t:CMakePredefinedTargets\INSTALL_RUNTIME -p:Configuration=RelWithDebInfo -p:Platform=x64 build\win64\WotWRandomizer.sln
          IF ERRORLEVEL 1 (
            echo BUILD FAILED
            exit 1
          )
      - name: Compiling AHK scripts
        shell: cmd
        timeout-minutes: 1
        run: |
          ".\ext\ahk\Ahk2Exe.exe" /silent /verbose /in ".\projects/AutoTracker/OriAutoTracker.ahk" /icon ".\WotwRando.ico" /out "C:\moon\ItemTracker.exe" > error.txt
          type error.txt
      - name: Archive randomizer
        uses: actions/upload-artifact@v2
        with:
          name: randomizer
          path: 'C:\moon\randomizer\*'
